### ISSUE TITLE
Should `DisposableStack` have a `disposed` property?

### ISSUE THREAD

**Issue by rbuckton** [tc39/proposal-explicit-resource-management#113]
Since a `DisposableStack` is no longer usable after it has been disposed, should we add a `disposed` property so that a user can check the current disposal state?

I don't have a strong preference, so I'm looking for feedback. Even without this property it is still possible to determine the state in user code via `try..catch` by attempting to add `null` or `undefined` as a resource:

```js
try {
  stack.use(null);
  // stack is not yet disposed
} catch {
  // stack is disposed
}
```

This works because `use` throws on entry if the stack is disposed but makes no other changes to the stack since the resource is `null`. We don't generally expose such a state in the standard library: `Promise` gives no indication of its fulfillment state, you can only determine if an `ArrayBuffer` is detached by attempting to use it (in which case it throws), etc.

**Comment by ljharb** [comment]
Relying on try/catch is the worst possible ergonomics, so I'd be in favor of a `disposed` accessor on the prototype.
