### ISSUE TITLE
Spec diff isn't rendering

### ISSUE THREAD

**Issue by codehag** [tc39/proposal-explicit-resource-management#227]
See title, currently the url for viewing the diff of the spec doesn't work: https://arai-a.github.io/ecma262-compare/?from=3d5a70b1b543a776dd5e255f8bfd877bf08bdc74&to=25f1bc4a4c19a0cc202d25567573d098e239b911

**Comment by rbuckton** [comment]
The correct url is https://arai-a.github.io/ecma262-compare/?pr=3000. This should be fixed now.
