### ISSUE TITLE
Consider Scala's By-Name Parameters

### ISSUE THREAD

**Issue by jehugaleahsa** [tc39/proposal-explicit-resource-management#24]
Another option to explicitly supporting resource management would be to add support for something like Scala's by-name parameters: https://docs.scala-lang.org/tour/by-name-parameters.html

To summarize, you have this weird syntax `param: => Result` that indicates that whatever expression is passed to that parameter should be evaluated *any time* `param` is evaluated in the function. In JavaScript, there'd be no need to specify a result type, so the syntax could be even cleaner. For the example below, I will just write `: =>` going to nothing, as a placeholder.

You'd end up implementing `using` like this:

```javascript
function using(resource: =>) {
    return (action) => {
        let data = null;
        try {
            data = resource; // be sure to only reference resource once
            return action(data);
        } finally {
              if (data != null) {
                  data.close(); // or whatever releases the resource
              }
        }
    };
}
```

And you'd call it like this:

```javascript
using(new Resource())(resource => doSomething(resource));
```

Note, that `: =>` is just syntactic sugar for passing a lambda, so you don't have to write `using(() => new Resource())...`.

**Comment by rbuckton** [comment]
I'm not sure how `: =>` helps in this scenario. The downside of `using` as a function is that it becomes very complicated to use in a generator or async function since you would have to `yield*` the result of calling `using` in a generator or `await` the result of calling `using` in an async function.
