### ISSUE TITLE
AggregateError should require `errors` argument to be an iterable

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-explicit-resource-management#27]
(This is a concern for a later stage, but I figured I'd open this now because otherwise I'll forget.)

In particular, it should not accept `undefined` and should not accept array-likes (nothing should accept array-likes, really).

At least, that's what the `Promise.any` proposal settled on in [this thread](https://github.com/tc39/proposal-promise-any/issues/14#issuecomment-468095969).

Likewise, that proposal makes `errors` enumerable, where this proposal makes it non-enumerable. Personally I think enumerable makes more sense, though it doesn't matter much.

**Comment by rbuckton** [comment]
Fixed in 633d5b68269ef7eeedd2052ef5826fa6d8e2763d.
