### ISSUE TITLE
use a more distinct keyword, possibly `try using` or `try with`

### ISSUE THREAD

**Issue by leobalter** [tc39/proposal-explicit-resource-management#31]
Regardless of being used in other languages, the `try (...) {}` syntax format seems aggressive to developer intuition and complexity.

One way to go past this would be adding a more distinguishable keyword.

My proposed solution is:

```js
try using (...) {}
```

Other alternative would be `try with (...) {}` but I wonder if this would find rejection from other delegates, so the first option might be easier to advance.

I'm intentionally omitting the syntax production for `(...)` in this issue as I consider it to be another topic to be solved separately.

**Comment by ExE-Boss** [comment]
`try with (foo) { … }` could imply that members of&nbsp;`foo` are&nbsp;in&nbsp;scope directly like in&nbsp;the&nbsp;sloppy mode only `with` statement, which is&nbsp;not what this proposal is&nbsp;about.
