### ISSUE TITLE
`if` statements

### ISSUE THREAD

**Issue by arcanis** [tc39/proposal-explicit-resource-management#32]
This proposal reminds me the [`if-with-initializer` statements](https://skebanga.github.io/if-with-initializer/) from C++17. The syntax is as such:

```c++
if (auto ret = map.insert({ "hello", 3 }); !ret.second)
    std::cout << "hello already exists with value " << ret.first->second << "\n";
```
 In JS, it would give something similar to this:

```js
if (const obj = get(); obj.length < 10)
  obj.push();
```

Which is quite close to the proposal:

```js
try (const obj = get()) {
  if (obj.length < 10) {
    obj.push();
  }
}
```

On one hand the `try` makes it more explicit that there's a trick, on the other hand the `if` makes it slightly less verbose, and is a pattern that already exists. Have you considered making initialized `if` statements an extension of the proposal? It could even become the main syntax with a slightly higher verbosity:

```js
if (const obj = get(); obj)
  obj.doSomething();
```

**Comment by rbuckton** [comment]
I don't think that fits with this proposal. There is a symmetry with `try`/`finally` and `try`-with-resources, in that a `try`-with-resources block essentially provides an implicit `finally` block in which the resource is disposed. The semantic meaning of `if` doesn't have anything to do with `finally`, so it would seem somewhat out of place.
