### ISSUE TITLE
Forbid binding patterns in 'try using (const ...)' (or 'using const')

### ISSUE THREAD

**Issue by rbuckton** [tc39/proposal-explicit-resource-management#42]
Per discussion in the February TC39, due to concerns on both sides of how destructured bindings should be disposed, we are opting to forbid binding patterns on these statements for this proposal. 

We can consider a future implementation of binding patterns in these cases as a follow on proposal.

**Comment by bergus** [comment]
For reference: https://github.com/tc39/notes/blob/master/meetings/2020-02/february-5.md#updates-on-explicit-resource-management
