### ISSUE TITLE
Add Node.js streams .destroy() as prior art

### ISSUE THREAD

**Issue by mcollina** [tc39/proposal-explicit-resource-management#44]
[`.destroy(err)`](https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_writable_destroy_error) is something every close to the spirit of this. We also have [`finished(stream, cb)`](https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_stream_finished_stream_options_callback) to be notified once a stream is "done", and [`pipeline(..streams, cb)`](https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_stream_pipeline_streams_callback) to make sure all streams are teared down correctly.

All of this is relevant prior art, and I think streams would benefit greatly from this addition. I'm happy to test/verify it would all work well with node streams as soon as there is transpilation support.

**Comment by rbuckton** [comment]
I've added a section to the explainer detailing how this would apply to the NodeJS APIs, but not as a specific reference in Prior Art as stream disposal is a fairly common characteristic across numerous languages and runtimes.
