### ISSUE TITLE
My own approach which might be interresting to you

### ISSUE THREAD

**Issue by julien-f** [tc39/proposal-explicit-resource-management#59]
Hi everyone,

For my own needs, I have developed my solution for resource management, inspired by C#, Python and Bluebird.

It's available in one of my libs and you may find it interesting: https://github.com/JsCommunity/promise-toolbox#resource-management

I'm here if you have any questions or remarks about it :slightly_smiling_face: 

If not, feel free to close this issue.

(Please don't look at the source and tests too close :sweat_smile: )

**Comment by rbuckton** [comment]
Thanks for the info.
