### ISSUE TITLE
e4a08a6f-7de8-4c15-b661-8d39d884aea7

### ISSUE THREAD

**Issue by Queens666** [tc39/proposal-explicit-resource-management#79]
https://source.cloud.google.com/results/invocations/e4a08a6f-7de8-4c15-b661-8d39d884aea7/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmain%2Fmacos%2Fbazel

**Comment by rbuckton** [comment]
I'm not sure what this is but it does not seem related to the proposal.
