### ISSUE TITLE
Promise.using and C# feedback

### ISSUE THREAD

**Issue by benjamingr** [tc39/proposal-explicit-resource-management#9]
Hey,

Thanks for this! 

There were a few interesting edge cases we ran into when doing `Promise.using` for bluebird and those resulted in some interesting discussion (and a blog post) a while ago.

I feel strongly about this feature and I think we need a better resource handling story for JavaScript. Especially for the multiple resource case. 

cc @ericlippert who answered https://stackoverflow.com/a/21123756/1348195 which is relevant.

**Comment by rbuckton** [comment]
As proposed, `using` here would have the same semantics as `using` in C#, namely that `using (let a = ..., b = ...) {}` is effectively the same as `using (let a = ...) { using(let b = ...) { } }`. The caveat mentioned by @ericlippert in the stackoverflow comment primarily speaks to the quality of code written by the author of the disposable resource.

If, for example, you implement your resource as this:

```js
const fs = require("fs");
class FileHandle {
  constructor(file) {
    const handle = fs.open(file, ...);
    blah();
    this.handle = handle;
  }
}
```

You would run into the same situation in his comment. The best way to address this is to ensure that unmanaged resources are handled in any exceptional case in the constructor:

```js
const fs = require("fs");
class FileHandle {
  constructor(file) {
    const handle = fs.open(file, ...);
    try {
      blah();
      this.handle = handle;
    }
    catch (e) {
      fs.close(handle); // failed to finish initialization, close the handle.
      throw e;
    }
  }
}
```

I believe this has less to do with the design of `using` and more to do with documentation, teaching, and user guidance over how to implement a disposable resource using `[Symbol.dispose]`.

**Comment by benjamingr** [comment]
I don't think this needs to remain open. Feel free to reopen if you feel differently.
