### ISSUE TITLE
PaymentRequest shouldn't always abort

### ISSUE THREAD

**Issue by acutmore** [tc39/proposal-explicit-resource-management#94]
Just a small thing

> PaymentRequest — @@asyncDispose() as an alias for abort()

Probably wouldn't want a direct alias for `abort` as Aborting after a successful payment request is an error. So would be a new method that conditionally aborts.

https://w3c.github.io/payment-request/#dom-paymentrequest-abort

**Comment by rbuckton** [comment]
That's fair. The current list is a very cursory glance at the feasibility of leveraging this capability in the DOM.
